services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env
    command: npm start
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=budgeting

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
